devonfw/my-thai-star

- java/mtsj/server/src/main/resources/logback.xml
This should do it... this time I even compiled and run the thing before the PR (shame on me!)
> fix loging only to console

- java/mtsj/core/pom.xml
- java/mtsj/pom.xml
- java/mtsj/server/pom.xml
commit done for issue https://github.com/oasp/oasp4j/issues/599
> Fix regression Java 1.8 and QueryDSL (see: https://github.com/oasp/oasp4j/issues/599 )

- angular/src/app/cockpit-area/order-cockpit/order-cockpit.component.ts
- angular/src/app/cockpit-area/reservation-cockpit/reservation-cockpit.component.ts
- angular/yarn.lock
When the user sorted multiple columns it was difficult to understand what items were really being sorted. The sort objects were accumulated and the arrows that marked the sort order were only visible at the latest column clicked. This way the user only can sort one column at the same time and the frontend works as expected.
> Fixed issues when sorting

- java/mtsj/core/src/main/java/io/oasp/application/mtsj/bookingmanagement/dataaccess/api/BookingEntity.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/bookingmanagement/logic/api/to/BookingCto.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/bookingmanagement/logic/api/to/BookingEto.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/bookingmanagement/service/api/rest/BookingmanagementRestService.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/bookingmanagement/service/impl/rest/BookingmanagementRestServiceImpl.java
> Validation changes

- angular/src/app/backend/backend.module.ts
- angular/src/app/backend/booking/booking-data-service.ts
- angular/src/app/backend/dishes/dishes-data-service.ts
- angular/src/app/backend/login/login-data-service.ts
- angular/src/app/backend/order/order-data-service.ts
- angular/src/app/backend/order/order-rest.service.ts
- angular/src/app/config.ts
This PR removes the warnings related with the circular dependencies detected by the latest versions of Angular CLI.
> Circular dependencies removed in angular code.

- java/mtsj/core/src/main/java/io/oasp/application/mtsj/bookingmanagement/dataaccess/impl/dao/BookingDaoImpl.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/bookingmanagement/dataaccess/impl/dao/InvitedGuestDaoImpl.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/dishmanagement/dataaccess/impl/dao/CategoryDaoImpl.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/dishmanagement/dataaccess/impl/dao/DishDaoImpl.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/dishmanagement/dataaccess/impl/dao/IngredientDaoImpl.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/imagemanagement/dataaccess/impl/dao/ImageDaoImpl.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/ordermanagement/dataaccess/impl/dao/OrderDaoImpl.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/ordermanagement/dataaccess/impl/dao/OrderLineDaoImpl.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/usermanagement/dataaccess/impl/dao/UserDaoImpl.java
- java/mtsj/core/src/main/java/io/oasp/application/mtsj/usermanagement/dataaccess/impl/dao/UserRoleDaoImpl.java
filters and orderBy's were case sensitive that was causing some undesired behaviours. This PR solves from the backend side.
> orderBy and filters case insensitive

- angular/karma.conf.js
- angular/package.json
- angular/yarn.lock
Besides, Karma config has been improved.
> Angular CLI updated to 1.5.2 to fix an issue with karma test runner.

- angular/package-lock.json
Now, with a `npm install` the correct dependencies will be installed as `yarn` does thanks to `yarn.lock`.
> Added package-lock.json

- java/passbook/src/main/java/com/capgemini/camel/IntegrationRoute.java
- java/passbook/src/main/resources/application.properties
- java/salesforcepoc/src/main/java/com/capgemini/salesforcepoc/IntegrationRoute.java
- java/salesforcepoc/src/main/resources/application.properties
passbook route for eMail transfer adapted (protocol changed)
> Verbose mode in passbook and salesforce microservice,

- README.md
- docker-compose.yml
- reverse-proxy/Dockerfile
- reverse-proxy/nginx.conf
Added 3rd container to the deployment: `reverse-proxy` and changed Angular's nginx configuration.
> Added reverse-proxy to the Docker Deployment independent from Angular client

- angular/src/app/home/home.component.html
- angular/src/app/home/home.component.scss
- angular/src/app/home/home.component.ts
Style component with css, not html attributes (where not needed), improved mobile view, removed deprecated css, moved data to .ts file to keep view definition not that tightly coupled with data.
> A proposal on how styling could (should?) be made.

- angular/src/app/animations/fade.animation.ts
- angular/src/app/app.component.html
- angular/src/app/app.component.scss
- angular/src/app/app.component.ts
A sample of Angular routing animations. This sample consists of a fade animation.
> Routing fade animation.

- angular/src/app/menu/menu.component.html
- angular/src/app/menu/menu.component.scss
Please note that I was not able to use server data, so tried to not touch the menu card - still as i did not see those, I might break something. Additionally layout of filters is not exactly the same, so before approving please compare.
This refactoring simplifies HTML structure of menu component before cutting it into smaller components. it also brings styling closer to scss.
> Refactor menu filters, improve mobile and tablet views

- angular/electron-builder.json
- angular/package.json
- angular/yarn.lock
**Issue number**
None
**Implementation details**
Update version number in `package.json` file and files section in `electron-builder.json`.
> Electron version updated to 2.0.8 to fix vulnerability and electron-builder files rule updated

- angular/src/app/cockpit-area/order-cockpit/order-cockpit.component.ts
- angular/src/app/cockpit-area/reservation-cockpit/reservation-cockpit.component.ts
- angular/src/app/menu/menu.component.ts
- angular/src/app/menu/shared/menu.service.ts
- java/mtsj/pom.xml
> Fixed issue #142 for migration to devon4j

- angular/e2e/dashboard.e2e.ts
- angular/src/app/app.component.ts
- angular/src/app/book-table/shared/book-table.service.ts
- angular/src/app/cockpit-area/order-cockpit/order-cockpit.component.spec.ts
- angular/src/app/cockpit-area/order-cockpit/order-cockpit.component.ts
- angular/src/app/cockpit-area/order-cockpit/order-dialog/order-dialog.component.ts
- angular/src/app/cockpit-area/reservation-cockpit/reservation-cockpit.component.spec.ts
- angular/src/app/cockpit-area/reservation-cockpit/reservation-dialog/reservation-dialog.component.ts
- angular/src/app/cockpit-area/shared/waiter-cockpit.service.ts
- angular/src/app/core/authentication/auth-guard.service.ts
- angular/src/app/core/authentication/auth.service.ts
- angular/src/app/core/core.module.ts
- angular/src/app/core/windowService/windowService.service.spec.ts
- angular/src/app/header/header.component.ts
- angular/src/app/home/home-card/home-card.component.ts
- angular/src/app/menu/menu-card/menu-card-details/menu-card-details.component.ts
- angular/src/app/menu/menu-card/menu-card.component.ts
- angular/src/app/menu/menu-filters/menu-filters.component.ts
- angular/src/app/menu/menu.component.html
- angular/src/app/menu/menu.component.spec.ts
- angular/src/app/menu/menu.component.ts
- angular/src/app/shared/directives/email-validator.directive.ts
- angular/src/app/shared/directives/equal-validator.directive.ts
- angular/src/app/sidenav/shared/sidenav.service.ts
- angular/src/app/sidenav/sidenav-order/sidenav-order.component.ts
- angular/src/app/sidenav/sidenav.component.html
- angular/tslint.json
- Rules upgraded.
- Fixed new linting errors
- Code readability improved.
> Linting updated to Angular 7

- README.adoc
- mrchecker/endtoend-test/pom.xml
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/common/readProperties/ConfigFileReader.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/common/utils/Utils.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiDateTimePage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiHomePage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiReservationsPage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiTableBodyPage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/tests/MyThaiStarTest.java
Removed some unnecessary prints, fixed a readme errata and added all the authors in some files they were missing.
> Cleaning code of some MrChecker tests and a readme errata regarding MrChecker

- angular/package.json
- angular/src/app/config.ts
- angular/src/environments/environment.docker.ts
- angular/src/environments/environment.net.ts
- angular/src/environments/environment.node.ts
- angular/src/environments/environment.prod.ts
- angular/src/environments/environment.prodcompose.ts
- angular/src/environments/environment.pwa.ts
- angular/src/environments/environment.ts
- angular/src/polyfills.ts
- angular/yarn.lock
- Fixed serve and build errors for IE. _Anyway some CSS and HTML adaptations must be done._
- Added types for config.
> Fixed serve and build for IE and config types added

- angular/Dockerfile
- reverse-proxy/nginx-consul/Dockerfile
- reverse-proxy/nginx-consul/consul-template.service
- reverse-proxy/nginx-consul/docker-compose.fromcode.yml
- reverse-proxy/nginx-consul/docker-compose.yml
- reverse-proxy/nginx-consul/nginx.conf
- reverse-proxy/nginx-consul/nginx.service
Added all files required to deploy the My Thai Star application ussing the NGINX-Consul approach. It will use the NGINX for load balancing and the Consul for service discovery. Also, it uses the consul-template in order to refresh the nginx.conf file.
> Added NGINX-Consul approach. Modified angular Dockerfile

- angular/src/app/cockpit-area/order-cockpit/order-cockpit.component.spec.ts
- angular/src/app/cockpit-area/reservation-cockpit/reservation-cockpit.component.spec.ts
- angular/src/app/core/config/config.service.ts
- angular/src/app/menu/menu.component.spec.ts
- docker-compose.yml
- reverse-proxy/docker-compose.yml
- reverse-proxy/nginx-consul/docker-compose.fromcode.yml
- reverse-proxy/nginx-consul/docker-compose.yml
As the PR #161 had some conflicts I forgot to pass the tests properly. This PR fixes the ConfigService and the tests.
> Angular tests fixed for PR #161

- java/mtsj/api/src/main/java/com/devonfw/application/mtsj/general/common/api/validation/EmailExtended.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/bookingmanagement/common/api/exception/CancelInviteNotAllowedException.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/bookingmanagement/dataaccess/api/BookingEntity.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/dishmanagement/dataaccess/api/DishEntity.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/common/api/validation/EmailExtended.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/dataaccess/api/ApplicationPersistenceEntity.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/security/JWTAuthenticationFilter.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/service/impl/config/BaseWebSecurityConfig.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/service/impl/config/ServiceConfig.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/service/impl/config/WebConfig.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/service/impl/rest/SecurityRestServiceImpl.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/ordermanagement/common/api/exception/CancelNotAllowedException.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/ordermanagement/common/api/exception/NoBookingException.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/ordermanagement/common/api/exception/NoInviteException.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/ordermanagement/common/api/exception/OrderAlreadyExistException.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/ordermanagement/dataaccess/api/OrderLineEntity.java
- java/mtsj/core/src/test/java/com/devonfw/application/mtsj/dishmanagement/logic/impl/DishmanagementTest.java
- java/mtsj/core/src/test/java/com/devonfw/application/mtsj/general/dataaccess/impl/config/BeansJpaConfig.java
Hi guys I just create a pull request with the easy quick wins to have the project of MyThaiStar in good shape.
Bear in mind that all the changes applied, were done avoiding changing the functionality. Some refactor is required to remove the type net.sf.mmm.util.filter.api.Filter and similar.
> Organizing imports, changing builders to non deprecated, cleaning, etc

- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/common/data/Reservation.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/common/data/User.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/common/mapper/UserMapper.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/common/readProperties/ConfigFileReader.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/common/utils/Utils.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiBookPage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiConfirmBookPage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiDateTimePage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiHomePage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiLoginPage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiMenuPage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiOrdersPage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiReservationsPage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiSummaryPage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiTableBodyPage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/pages/ThaiWaiterPage.java
- mrchecker/endtoend-test/src/test/java/com/devonfw/mts/tests/MyThaiStarTest.java
I removed each "@author" in all src resources
> delete some comments

- angular/README.md
Removed npm installation as yarn is the default package manager.
> README Angular update

- java/mtsj/api/src/main/java/com/devonfw/application/mtsj/bookingmanagement/common/api/Booking.java
- java/mtsj/api/src/main/java/com/devonfw/application/mtsj/bookingmanagement/common/api/InvitedGuest.java
- java/mtsj/api/src/main/java/com/devonfw/application/mtsj/bookingmanagement/common/api/to/BookingEto.java
- java/mtsj/api/src/main/java/com/devonfw/application/mtsj/bookingmanagement/common/api/to/BookingSearchCriteriaTo.java
- java/mtsj/api/src/main/java/com/devonfw/application/mtsj/bookingmanagement/common/api/to/InvitedGuestEto.java
- java/mtsj/api/src/main/java/com/devonfw/application/mtsj/bookingmanagement/common/api/to/InvitedGuestSearchCriteriaTo.java
- java/mtsj/api/src/main/java/com/devonfw/application/mtsj/general/common/api/validation/EmailExtended.java
- java/mtsj/architecture.json
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/bookingmanagement/dataaccess/api/BookingEntity.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/bookingmanagement/dataaccess/api/InvitedGuestEntity.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/bookingmanagement/dataaccess/api/repo/BookingRepository.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/bookingmanagement/dataaccess/api/repo/InvitedGuestRepository.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/bookingmanagement/logic/impl/BookingmanagementImpl.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/common/base/JWTAuthenticationFilter.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/dataaccess/api/ApplicationPersistenceEntity.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/ordermanagement/logic/impl/OrdermanagementImpl.java
- java/mtsj/core/src/main/resources/config/app/common/dozer-mapping.xml
- java/mtsj/core/src/test/java/com/devonfw/application/mtsj/general/common/AccessControlSchemaXmlValidationTest.java
- java/mtsj/pom.xml
1. This PR contains all the remaining updates for PR https://github.com/devonfw/my-thai-star/pull/198
Review comments given in PR #192 has been updated in this PR
Important updates are :
Java.time.Instant
Getting the URL of frontend application that needs to be put in email
imp: This PR is dependent on devon4j PR https://github.com/devonfw/devon4j/pull/64
For testing this PR, it will require latest devon4j 3.1.0
> Java.time.Instant and client URL changes - Updated for PR #198

- angular/package-lock.json
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/mailservice/logic/impl/MailImpl.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/mailservice/logic/impl/MailMock.java
- java/mtsj/core/src/main/resources/application.properties
- java/mtsj/core/src/main/resources/config/application.properties
- java/mtsj/core/src/main/resources/db/specific/h2/V0001__R001_Create_schema.sql
Getting CG mail at the time of booking the table.
> Issue #204 -Setup CG SMTP Configuration 

- angular/src/app/app.component.ts
- angular/src/app/cockpit-area/prediction-cockpit/prediction-cockpit.component.ts
- angular/src/app/core/authentication/auth-guard.service.ts
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/dishmanagement/logic/impl/DishmanagementImpl.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/common/impl/security/BaseUserDetailsService.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/service/impl/LoginController.java
- java/mtsj/core/src/main/java/com/devonfw/application/mtsj/mailservice/logic/impl/MailImpl.java
SonarQube was flagging 4 Vulnerabilities.
I fixed 3 of them and I avoid one because Vaibhav tell me that Iwan request one line in LoginController.java that Sonar mark as an important blocker. For that reason I added NOSONAR to avoid the analysis.
> fix logs and avoid one line

- .travis.yml
Travis CI config merged using two stages: 
- The already existing docker builds.
- The new documentation workflow
> Travis CI config updated with stages

- angular/Dockerfile.travis
- angular/src/app/user-area/shared/user-area.service.ts
The only thing that I did is to execute the pettier in the file  _angular/src/app/user-area/shared/user-area.service.ts_
> Fixed linting problems at user-area.service.ts file

- angular/src/app/cockpit-area/order-cockpit/order-cockpit.component.html
- angular/src/app/cockpit-area/order-cockpit/order-dialog/order-dialog.component.html
- angular/src/app/cockpit-area/reservation-cockpit/reservation-cockpit.component.html
- angular/src/app/cockpit-area/reservation-cockpit/reservation-dialog/reservation-dialog.component.html
Date was not displaying in proper format
> Fix date issue

- documentation/_Sidebar.asciidoc
- documentation/deployment.asciidoc
- documentation/traefik-reverse-proxy.asciidoc
- jenkins/angular/deployment/Jenkinsfile
Added traefik documentation.
Also, I updated angular deployment pipeline to be able to run in the new PL version
> Added traefik documentation. 

- java/mtsj/core/src/main/resources/db/migration/V0005__R001_Master_data.sql
Issue - https://github.com/devonfw/my-thai-star/issues/275
Users  (Cook ,Barkeeper,Chief) completely removed from backend side and can't be login with them.
If want to get any specific notification when login with above users like "user is not implemented yet" then need to handle it UI side with other separate  PR.
> Removed Unnecessary User role (Cook ,Barkeeper,Chief)

- docker-compose.traefik.yml
- reverse-proxy/traefik/docker-compose.yml
In this PR I changed the traefik version inside the docker-compose.yml from 2.0.0 to 2.0 as described by @markusschuh in the issue #280 
@markusschuh can you check if this is correct and then we can close those issue?
> Changed traefik version from 2.0.0 to 2.0

- java/mtsj/batch/src/main/java/com/devonfw/application/mtsj/SpringBootBatchApp.java
Fixed issue https://github.com/devonfw/my-thai-star/issues/303
> fixed mtsj bootified error

- java/Dockerfile
- java/Dockerfile.openshift
- java/Dockerfile.travis
- reverse-proxy/java/Dockerfile
All java Dockerfiles updated in order to use OpenJDK 11
> Update all java Dockerfiles to java11

- java/mtsj/core/src/test/java/com/devonfw/application/mtsj/clustermanagement/logic/impl/ClustermanagementTest.java
- java/mtsj/core/src/test/java/com/devonfw/application/mtsj/dishmanagement/logic/impl/DishmanagementTest.java
- java/mtsj/core/src/test/java/com/devonfw/application/mtsj/general/common/AccessControlSchemaXmlValidationTest.java
- java/mtsj/core/src/test/java/com/devonfw/application/mtsj/general/common/PermissionCheckTest.java
- java/mtsj/core/src/test/java/com/devonfw/application/mtsj/general/common/base/Devon4jPackageCheckTest.java
- java/mtsj/core/src/test/java/com/devonfw/application/mtsj/imagemanagement/logic/impl/ImagemanagementTest.java
- java/mtsj/core/src/test/java/com/devonfw/application/mtsj/ordermanagement/logic/impl/OrdermanagementTest.java
- java/mtsj/core/src/test/java/com/devonfw/application/mtsj/predictionmanagement/logic/impl/PredictionmanagementTest.java
- java/mtsj/pom.xml
Upgrade to devon4j 2.3.1 and with Junit 5
> ugrade to devon4j 2.3.1

- angular/Dockerfile
- angular/Dockerfile.travis
- node/Dockerfile
Removed the line `RUN npm i -g yarn` as now the node:lts docker image already contains yarn.
> Removed unnecessary line at Dockerfile

- jenkins/README.md
- jenkins/angular/cicd/Jenkinsfile
- jenkins/angular/deployment/Jenkinsfile
- jenkins/deployment/Jenkinsfile
- jenkins/java/deployment/Jenkinsfile
Updated the Jenkinsfiles placeholders in order to remove the internal URL to our PL.
> Updated Jenkinsfiles placeholders

- java/Dockerfile
> Java container healthcheck fix

- angular/src/app/book-table/store/effects/book-table.effects.ts
- angular/src/app/user-area/store/effects/auth.effects.ts
Hi @sujith-mn, @suprishi,
Request you to review the changes for the Login issue after logout. Please let me know incase any issue.
Thanks,
Dattu
> Login Refresh issue fix
